name: manilakbay
description: Metro Manila commute guide app
publish_to: 'none'
version: 0.0.0+1
environment:
  sdk: ^3.11.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  cached_network_image: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/data/